image: node:latest

stages:
  - .pre
  - test
  - build

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: .pre
  script:
    - yarn

test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
